const entries = [
  "ancient arrow",
  "ancient battle axe",
  "ancient battle axe+",
  "ancient battle axe++",
  "ancient bladesaw",
  "ancient bow",
  "ancient shield",
  "ancient short sword",
  "ancient spear",
  "apple",
  "armoranth",
  "armored carp",
  "armored porgy",
  "arrow",
  "big hearty radish",
  "big hearty truffle",
  "black bokoblin",
  "black hinox",
  "black lizalfos",
  "black moblin",
  "bladed rhino beetle",
  "blizzard rod",
  "blizzrobe",
  "blue bokoblin",
  "blue hinox",
  "blue lizalfos",
  "blue moblin",
  "blue nightshade",
  "blue sparrow",
  "blue-maned lynel",
  "blue-winged heron",
  "blupee",
  "boat oar",
  "boko bat",
  "boko bow",
  "boko club",
  "boko shield",
  "boko spear",
  "bokoblin arm",
  "bokoblin",
  "bomb arrow",
  "boomerang",
  "boulder breaker",
  "bow of light",
  "bright-chested duck",
  "bright-eyed crab",
  "bushy-tailed squirrel",
  "calamity ganon",
  "ceremonial trident",
  "chillfin trout",
  "chillshroom",
  "chuchu",
  "cobble crusher",
  "cold darner",
  "cold-footed wolf",
  "common sparrow",
  "cool safflina",
  "courser bee honey",
  "cucco",
  "cursed bokoblin",
  "cursed lizalfos",
  "cursed moblin",
  "dark beast ganon",
  "daybreaker",
  "decayed guardian",
  "demon carver",
  "dinraal",
  "donkey",
  "double axe",
  "dragon bone boko bow",
  "dragonbone boko bat",
  "dragonbone boko club",
  "dragonbone boko shield",
  "dragonbone boko spear",
  "dragonbone moblin club",
  "dragonbone moblin spear",
  "drillshaft",
  "duplex bow",
  "edge of duality",
  "eightfold blade",
  "eightfold longblade",
  "eldin ostrich",
  "electric chuchu",
  "electric darner",
  "electric keese",
  "electric lizalfos",
  "electric safflina",
  "electric wizzrobe",
  "emblazoned shield",
  "endura carrot",
  "endura shroom",
  "energetic rhino beetle",
  "enhanced lizal spear",
  "fairy",
  "falcon bow",
  "farmer's pitchfork",
  "farming hoe",
  "farosh",
  "feathered edge",
  "feathered spear",
  "fire arrow",
  "fire chuchu",
  "fire keese",
  "fire rod",
  "fire wizzrobe",
  "fire-breath lizalfos",
  "fireblight ganon",
  "fireproof lizard",
  "fisherman's shield",
  "fishing harpoon",
  "flameblade",
  "flamespear",
  "fleet-lotus seeds",
  "forest dweller's bow",
  "forest dweller's shield",
  "forest dweller's spear",
  "forest dweller's sword",
  "forest octorok",
  "forked lizal spear",
  "fortified pumpkin",
  "frost pebblit",
  "frost talus",
  "frostblade",
  "frostspear",
  "gerudo scimitar",
  "gerudo shield",
  "gerudo spear",
  "giant boomerang",
  "giant horse",
  "golden bow",
  "golden claymore",
  "golden sparrow",
  "grassland fox",
  "great eagle bow",
  "great flameblade",
  "great frostblade",
  "great thunderblade",
  "great-horned rhinoceros",
  "grizzlemaw bear",
  "guardian scout i",
  "guardian scout ii",
  "guardian scout iii",
  "guardian scout iv",
  "guardian shield",
  "guardian shield+",
  "guardian shield++",
  "guardian skywatcher",
  "guardian spear",
  "guardian spear+",
  "guardian spear++",
  "guardian stalker",
  "guardian sword",
  "guardian sword+",
  "guardian sword++",
  "guardian turret",
  "hateno cow",
  "hearty bass",
  "hearty blueshell snail",
  "hearty durian",
  "hearty lizard",
  "hearty radish",
  "hearty salmon",
  "hearty truffle",
  "highland sheep",
  "hightail lizard",
  "hinox",
  "honeyvore bear",
  "horse",
  "hot-footed frog",
  "hotfeather pigeon",
  "hunter's shield",
  "hydromelon",
  "hylian retriever",
  "hylian shield",
  "hylian shroom",
  "hyrule bass",
  "hyrule herb",
  "ice arrow",
  "ice chuchu",
  "ice keese",
  "ice rod",
  "ice wizzrobe",
  "ice-breath lizalfos",
  "igneo pebblit",
  "igneo talus titan",
  "igneo talus",
  "iron sledgehammer",
  "ironshell crab",
  "ironshroom",
  "islander hawk",
  "keese",
  "kite shield",
  "knight's bow",
  "knight's broadsword",
  "knight's claymore",
  "knight's halberd",
  "knight's shield",
  "korok leaf",
  "lightning rod",
  "lightscale trident",
  "lizal boomerang",
  "lizal bow",
  "lizal forked boomerang",
  "lizal shield",
  "lizal spear",
  "lizal tri-boomerang",
  "lizalfos arm",
  "lizalfos",
  "lord of the mountain",
  "luminous ore deposit",
  "lynel bow",
  "lynel crusher",
  "lynel shield",
  "lynel spear",
  "lynel sword",
  "lynel",
  "maraudo wolf",
  "master kohga",
  "master sword",
  "meteo wizzrobe",
  "meteor rod",
  "mighty bananas",
  "mighty carp",
  "mighty lynel bow",
  "mighty lynel crusher",
  "mighty lynel shield",
  "mighty lynel spear",
  "mighty lynel sword",
  "mighty porgy",
  "mighty thistle",
  "moblin arm",
  "moblin club",
  "moblin spear",
  "moblin",
  "molduga",
  "molduking",
  "monk maz koshia",
  "moonlight scimitar",
  "mountain buck",
  "mountain crow",
  "mountain doe",
  "mountain goat",
  "naydra",
  "one-hit obliterator",
  "ore deposit",
  "palm fruit",
  "patricia",
  "phrenic bow",
  "pink heron",
  "pot lid",
  "radiant shield",
  "rainbow pigeon",
  "rainbow sparrow",
  "rare ore deposit",
  "razorclaw crab",
  "razorshroom",
  "red sparrow",
  "red-tusked boar",
  "reinforced lizal shield",
  "restless cricket",
  "rock octorok",
  "royal bow",
  "royal broadsword",
  "royal claymore",
  "royal guard's bow",
  "royal guard's claymore",
  "royal guard's shield",
  "royal guard's spear",
  "royal guard's sword",
  "royal halberd",
  "royal shield",
  "rugged rhino beetle",
  "rushroom",
  "rusty broadsword",
  "rusty claymore",
  "rusty halberd",
  "rusty shield",
  "sand seal",
  "sand sparrow",
  "sanke carp",
  "savage lynel bow",
  "savage lynel crusher",
  "savage lynel shield",
  "savage lynel spear",
  "savage lynel sword",
  "scimitar of the seven",
  "seagull",
  "sentry",
  "serpentine spear",
  "shield of the mind's eye",
  "shock arrow",
  "silent princess",
  "silent shroom",
  "silver bokoblin",
  "silver bow",
  "silver lizalfos",
  "silver longsword",
  "silver lynel",
  "silver moblin",
  "silver shield",
  "silverscale spear",
  "sizzlefin trout",
  "smotherwing butterfly",
  "sneaky river snail",
  "snow octorok",
  "snowcoat fox",
  "soldier's bow",
  "soldier's broadsword",
  "soldier's claymore",
  "soldier's shield",
  "soldier's spear",
  "soup ladle",
  "spicy pepper",
  "spiked boko bat",
  "spiked boko bow",
  "spiked boko club",
  "spiked boko shield",
  "spiked boko spear",
  "spiked moblin club",
  "spiked moblin spear",
  "spring-loaded hammer",
  "stalhorse",
  "stalizalfos",
  "stalkoblin",
  "stalmoblin",
  "stalnox",
  "stamella shroom",
  "staminoka bass",
  "stealthfin trout",
  "steel lizal bow",
  "steel lizal shield",
  "stone pebblit",
  "stone smasher",
  "stone talus (luminous)",
  "stone talus (rare)",
  "stone talus",
  "strengthened lizal bow",
  "summerwing butterfly",
  "sunset firefly",
  "sunshroom",
  "swallow bow",
  "swift carrot",
  "swift violet",
  "tabantha moose",
  "throwing spear",
  "thunder wizzrobe",
  "thunderblade",
  "thunderblight ganon",
  "thunderspear",
  "thunderstorm rod",
  "thunderwing butterfly",
  "tireless frog",
  "torch",
  "traveler's bow",
  "traveler's claymore",
  "traveler's shield",
  "traveler's spear",
  "traveler's sword",
  "treasure chest",
  "treasure octorok",
  "tree branch",
  "vicious sickle",
  "voltfin trout",
  "voltfruit",
  "warm darner",
  "warm safflina",
  "wasteland coyote",
  "water buffalo",
  "water octorok",
  "waterblight ganon",
  "white goat",
  "white horse",
  "white pigeon",
  "white-maned lynel",
  "wildberry",
  "windblight ganon",
  "windcleaver",
  "winterwing butterfly",
  "wood pigeon",
  "woodcutter's axe",
  "wooden bow",
  "wooden mop",
  "wooden shield",
  "woodland boar",
  "yiga blademaster",
  "yiga footsoldier",
  "zapshroom",
  "zora spear",
  "zora sword"
]
